#!/bin/bash

###############################################################################
#
# sudotask is Copyright (c) 2019 Alberto Lopez Siemens
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted under the conditions of the BSD LICENSE file at
# the rpi-snapshot github source repository:
#    https://github.com/AlbertoLopSie/sudo_cmd
#
# creates a shell script to be executed by cron job sudoexec
###############################################################################

##################################################
# Sets global variables
##################################################
version=1.0.0

PGM=`basename $0`

##################################################
# Verifies <user> argument supplied
##################################################
if [ "$1" == "" ]
then
  printf "\n   usage: $PGM cmd [-status ha-sensor] <args>\n\n"
  exit 1
fi

basedir="$HOME/.sudoexec"
cmd="$basedir/$1.cmd"
status="$basedir/$1.status"
exstat="$basedir/$1.exit"
stdout="$basedir/$1.stdout"
sensor="$basedir/$1.sensor"

cmdtext="#!/bin/bash\n"

report_status()
{
  echo $1 > $status

  if [ "$ha_sensor" != "" ]; then
    set_ha_sensor $ha_sensor $1
  fi
}

shift
if [ "$1" == "-status" ]; then
  shift
  ha_sensor=$1
  echo -e $ha_sensor > $sensor
  shift
fi

for var in "$@"
do
    cmdtext="$cmdtext$var "
done

#echo $cmd
rm -f $exstat
touch $exstat
rm -f $stdout
touch $stdout
#echo "Waiting" > $status
report_status "Waiting"
echo -e $cmdtext > $cmd
